language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - PmaPasswordEncoderBundleTestCase

before_script:
  - composer self-update
  - composer install

script: phpunit -c phpunit.xml.dist --coverage-text

notifications:
  email:
    - philipp.marien@gmail.com
